Feature/us 17 realisation steps
WildCodeSchool-2024-09/JS-Nantes-P2-Cafeotheque pull request #17
Opened 2024-11-13 11:30 UTC by naiiipan44

2024-11-13 16:23 UTC, MrLootman requested changes
Attention aux sélecteurs sans spécificité. Changement requis.

2024-11-13 16:23 UTC, MrLootman commented on client/src/pages/RecipeePage/PreparationSteps.css
Il n'est pas pertinent de prendre le sélecteur main comme tu l'as fait ici, et de lui attribuer un `display: flex`.
Le fait de ne pas rendre cette balise spécifique implique que toutes les balises main partout dans l'application vont se voir attribuer ce display.
Il faut donc être plus spécifique.

2024-11-13 16:23 UTC, Idirzz approved these changes

2024-11-15 13:23 UTC, MrLootman approved these changes
👍

2024-11-15 13:24 UTC, MrLootman approved these changes

2024-11-15 13:24 UTC, merged