Feature/us 07/show filters
WildCodeSchool-2024-09/JS-Nantes-P2-Cafeotheque pull request #25
Opened 2024-11-14 15:30 UTC by FarCodeFR

2024-11-14 15:32 UTC, MellerinCharly approved these changes
It's ok !

2024-11-14 15:38 UTC, MrLootman requested changes

2024-11-14 15:38 UTC, MrLootman commented on client/src/components/FilteredList.tsx
> +    console.warn(handleClick);
Ce `console.warn` devrait être éliminé du code.

2024-11-14 15:38 UTC, MrLootman commented on client/src/components/FilteredList.tsx
> +  }
Cette interface devrait être isolée dans un fichier à part, et être écrite en PacalCase..

2024-11-14 15:38 UTC, MrLootman commented on client/src/components/FilteredList.tsx
> +          <input onClick={handleClick} type="checkbox" id="pays" name="pays" />
Un élément `ul` ne devrait pas comporter autre chose que des listes en élément enfant. Question de référencement et d'accessibilité.

2024-11-15 08:12 UTC, FarCodeFR commented on client/src/components/FilteredList.tsx
> +          <input onClick={handleClick} type="checkbox" id="pays" name="pays" />
J'ai remplacé les UL par des section

2024-11-15 10:03 UTC, MrLootman requested changes

2024-11-15 10:03 UTC, MrLootman commented on client/src/components/FilteredList.tsx
> +    // { status: false, checked: [] }
Code mort, à supprimer avant intégration sur `dev`

2024-11-15 10:03 UTC, MrLootman commented on client/src/types/FilteredList.d.ts
> +export interface dataModel {
L'interface doit être écrite en PascalCase

---> https://ts.dev/style/#syntax

2024-11-15 10:33 UTC, MrLootman approved these changes

2024-11-15 10:33 UTC, merged