Feature 14/list favorite items
WildCodeSchool-2024-09/JS-Nantes-P2-Cafeotheque pull request #27
Opened 2024-11-15 10:29 UTC by Idirzz

2024-11-15 13:39 UTC, MrLootman commented
Conflits à résoudre.

2024-11-15 14:01 UTC, MrLootman requested changes

2024-11-15 14:01 UTC, MrLootman commented on client/src/components/NbrOfElementsPerPage.tsx
> +                if (e.key === "Enter") () => handleClickNumberOfElems(el);
Il aurait été plus intéressant d'utiliser un élément bouton plutôt que d'alourdir un élément `li` d'un attribut "onKeyDown".
Sémantiquement, si l'élément est cliquable et focusable, c'est un `button`.
C'est important pour des raisons d'accessibilité (la navigation au clavier est prise en charge nativement avec des éléments `button`), et les lecteurs d'écrans peuvent avertir un utilisateur mal-voyant qu'il s'agit d'un `button`.
A changer.

2024-11-15 14:01 UTC, MrLootman commented on client/src/components/Pagination.tsx
> +}
Il ferait bon d'isoler les interfaces dans un fichier spécifique, comme `pagination.d.ts`. Cela augmentera la lisibilité des composants.

2024-11-15 14:01 UTC, MrLootman commented on client/src/components/Pagination.tsx
> +          }}
Idem ici. L'img devrait être wrappé d'un élément `button`, ce qui évite un contournement sémantique.

2024-11-15 14:01 UTC, MrLootman commented on client/src/components/Pagination.tsx
> +          }}
Idem ici (cf. commentaire sur l'accessibilité).

2024-11-18 09:32 UTC, Idirzz commented
Fixed : ajout type PaginationProps file + button HTML tag used correctly as asked

2024-11-19 15:29 UTC, MrLootman approved these changes

2024-11-19 15:29 UTC, merged