🗃️: Create mock of data waiting for API
WildCodeSchool-2024-09/JS-Nantes-P2-Cafeotheque pull request #3
Opened 2024-11-07 15:43 UTC by Idirzz

2024-11-07 15:47 UTC, FarCodeFR approved these changes

2024-11-07 15:53 UTC, Jeremy-Mrz commented on client/src/mocks/apiMock.json
> +    "name": "Espresso Italien",
The start id from a database is usually 1

2024-11-07 15:55 UTC, Jeremy-Mrz requested changes
Nice API, you just need to update the id of the first item (see comment)

2024-11-08 10:30 UTC, FarCodeFR approved these changes

2024-11-08 10:33 UTC, Jeremy-Mrz approved these changes
Perfect

2024-11-08 10:33 UTC, merged