Feature/us 18 recipe video
WildCodeSchool-2024-09/JS-Nantes-P2-Cafeotheque pull request #31
Opened 2024-11-18 14:45 UTC by naiiipan44

2024-11-18 14:47 UTC, Idirzz approved these changes

2024-11-18 14:51 UTC, naiiipan44 commented
Le css de la liste des ingrédients et des étapes de réalisation a été réagencé dans une branche ultérieure dédié appelé US-42 : fix us-16 et us-17. L'affichage sera de nouveau " beau " une fois que j'aurais pushé cette branche. Comme j'avais créé la branche us-17 à partir de la branche 16 mon travail s'est " perdu ". Avec le groupe nous avons opté pour créer cette branche US-42 dédiée à réinjecter dans le dev plutôt que s'enliser dans une cherry pick chronophage "

2024-11-18 15:53 UTC, MrLootman approved these changes
Le nommage des fichiers est bon, la syntaxe est respectée dans les différentes conventions. Continue comme ça.

2024-11-18 15:55 UTC, MrLootman requested changes

2024-11-18 15:55 UTC, MrLootman commented on client/src/components/RecipeVideo.tsx
> +          </a>
Est-il prévu que la vidéo écrase le projet actuel, ou qu'elle s'ouvre dans un nouvel onglet ?
En l'état : on sort complètement du site en cliquant sur le lien, ce qui n'est pas souhaitable.

2024-11-19 14:49 UTC, naiiipan44 commented on client/src/components/RecipeVideo.tsx
> +          </a>
Les lignes ont été supprimées

2024-11-19 15:30 UTC, MrLootman approved these changes

2024-11-19 15:30 UTC, merged