Feature/us09 information product
WildCodeSchool-2024-09/JS-Nantes-P2-Cafeotheque pull request #38
Opened 2024-11-20 09:54 UTC by Idirzz

2024-11-20 14:18 UTC, Jeremy-Mrz requested changes

2024-11-20 14:18 UTC, Jeremy-Mrz commented on client/src/pages/CoffeeDetailPage/CoffeeDetailPage.css
> +}
Le style affectant le CSS générale de l'app (:root, body...) est à placer de préférence dans un fichier de CSS global.

2024-11-20 14:18 UTC, Jeremy-Mrz commented on client/src/pages/CoffeeDetailPage/CoffeeDetailPage.tsx
> +      setAlikeItems(alikeItems);
L'utilisation des `let` n'est pas une erreur à proprement parler, mais c'est une façon d'écrire un peu étrange.
Comme tu effectues 2 requêtes distinctes, sur un id spécifique puis sur un ensemble, tu peux renommer tes requêtes tel que `fetchCofeeReponse` & `fetchCofeesResponse` ( a titre d'exemple, tu peux trouver mieux ).

2024-11-20 14:19 UTC, Jeremy-Mrz commented
Confligt de merge avec : `client/src/models/DataModels.tsx`

2024-11-20 15:16 UTC, Idirzz commented on client/src/pages/CoffeeDetailPage/CoffeeDetailPage.css
> +}
fixed !

2024-11-20 15:19 UTC, Idirzz commented
fixed conflicts

2024-11-21 10:26 UTC, Jeremy-Mrz approved these changes
👍

2024-11-21 10:26 UTC, merged