Feature/us19 history coffee
WildCodeSchool-2024-09/JS-Nantes-P2-Cafeotheque pull request #46
Opened 2024-11-22 08:13 UTC by FarCodeFR

2024-11-22 10:17 UTC, Jeremy-Mrz requested changes

2024-11-22 10:17 UTC, Jeremy-Mrz commented on client/src/components/HistoryPage/HistoryCard.tsx
> +    <section id="historyTop" className="container-central-history">
les id et les class sont à écrire en kebab-case, `history-top`

2024-11-22 10:17 UTC, Jeremy-Mrz commented on client/src/pages/HistoryPage/HistoryOfCoffeePage.tsx
> +// Définir les types pour l'état
Commentaire superflu

2024-11-22 10:19 UTC, Jeremy-Mrz commented
Pour ta constante `cards` dans `client/src/pages/HistoryPage/HistoryOfCoffeePage.tsx` : 
Soit tu peux sortir la constante de ton component et la mettre en haut de ton fichier ( en dessous des imports )
Soit tu peux la déplacer dans un autre fichier (du style fichier de data ou de mocker ) et l'importer. 
Ca permettra de rendre ton code et ton component plus léger

2024-11-22 11:03 UTC, FarCodeFR commented on client/src/components/HistoryPage/HistoryCard.tsx
> +    <section id="historyTop" className="container-central-history">
Remplacement des id en kebab-case

2024-11-22 11:04 UTC, FarCodeFR commented on client/src/pages/HistoryPage/HistoryOfCoffeePage.tsx
> +// Définir les types pour l'état
Commentaire supprimé

2024-11-22 14:47 UTC, Jeremy-Mrz requested changes

2024-11-22 14:47 UTC, Jeremy-Mrz commented on client/src/pages/HistoryPage/HistoryAccueil.css
> +}
Il faut éviter les majuscules sur les noms de classe

2024-11-22 15:28 UTC, FarCodeFR commented on client/src/pages/HistoryPage/HistoryAccueil.css
> +}
Je viens d'effectuer les modifications ✅

2024-11-25 09:46 UTC, Jeremy-Mrz approved these changes

2024-11-25 09:47 UTC, merged